local M = {}

-- CSS properties with common values (optimized subset for performance)
M.properties = {
	-- Layout
	"display",
	"position",
	"top",
	"right",
	"bottom",
	"left",
	"width",
	"height",
	"min-width",
	"min-height",
	"max-width",
	"max-height",
	"margin",
	"margin-top",
	"margin-right",
	"margin-bottom",
	"margin-left",
	"padding",
	"padding-top",
	"padding-right",
	"padding-bottom",
	"padding-left",
	"box-sizing",
	"overflow",
	"overflow-x",
	"overflow-y",
	"z-index",

	-- Flexbox
	"flex",
	"flex-direction",
	"flex-wrap",
	"flex-flow",
	"flex-grow",
	"flex-shrink",
	"flex-basis",
	"justify-content",
	"align-items",
	"align-content",
	"align-self",
	"order",
	"gap",
	"row-gap",
	"column-gap",

	-- Grid
	"grid",
	"grid-template",
	"grid-template-columns",
	"grid-template-rows",
	"grid-template-areas",
	"grid-column",
	"grid-row",
	"grid-area",
	"grid-auto-flow",
	"grid-auto-columns",
	"grid-auto-rows",
	"grid-column-start",
	"grid-column-end",
	"grid-row-start",
	"grid-row-end",

	-- Typography
	"color",
	"font",
	"font-family",
	"font-size",
	"font-weight",
	"font-style",
	"line-height",
	"letter-spacing",
	"text-align",
	"text-decoration",
	"text-transform",
	"text-indent",
	"text-overflow",
	"white-space",
	"word-break",
	"word-wrap",

	-- Background
	"background",
	"background-color",
	"background-image",
	"background-size",
	"background-position",
	"background-repeat",
	"background-attachment",
	"background-clip",

	-- Border
	"border",
	"border-width",
	"border-style",
	"border-color",
	"border-radius",
	"border-top",
	"border-right",
	"border-bottom",
	"border-left",
	"border-top-left-radius",
	"border-top-right-radius",
	"border-bottom-left-radius",
	"border-bottom-right-radius",

	-- Visual
	"opacity",
	"visibility",
	"box-shadow",
	"filter",
	"backdrop-filter",
	"transform",
	"transform-origin",
	"transition",
	"animation",
	"cursor",

	-- Other
	"content",
	"outline",
	"list-style",
	"user-select",
	"pointer-events",
}

-- Common property values
M.values = {
	display = { "block", "inline", "inline-block", "flex", "inline-flex", "grid", "inline-grid", "none", "contents" },
	position = { "static", "relative", "absolute", "fixed", "sticky" },
	["flex-direction"] = { "row", "row-reverse", "column", "column-reverse" },
	["flex-wrap"] = { "nowrap", "wrap", "wrap-reverse" },
	["justify-content"] = { "flex-start", "flex-end", "center", "space-between", "space-around", "space-evenly" },
	["align-items"] = { "flex-start", "flex-end", "center", "baseline", "stretch" },
	["align-content"] = { "flex-start", "flex-end", "center", "space-between", "space-around", "stretch" },
	["text-align"] = { "left", "right", "center", "justify" },
	["text-transform"] = { "none", "uppercase", "lowercase", "capitalize" },
	["text-decoration"] = { "none", "underline", "overline", "line-through" },
	["font-weight"] = {
		"100",
		"200",
		"300",
		"400",
		"500",
		"600",
		"700",
		"800",
		"900",
		"normal",
		"bold",
		"bolder",
		"lighter",
	},
	["font-style"] = { "normal", "italic", "oblique" },
	["white-space"] = { "normal", "nowrap", "pre", "pre-wrap", "pre-line" },
	["word-break"] = { "normal", "break-all", "keep-all", "break-word" },
	["overflow"] = { "visible", "hidden", "scroll", "auto" },
	["overflow-x"] = { "visible", "hidden", "scroll", "auto" },
	["overflow-y"] = { "visible", "hidden", "scroll", "auto" },
	visibility = { "visible", "hidden", "collapse" },
	cursor = { "auto", "pointer", "default", "text", "move", "not-allowed", "grab", "grabbing" },
	["user-select"] = { "none", "auto", "text", "all" },
	["pointer-events"] = { "auto", "none" },
	["box-sizing"] = { "content-box", "border-box" },
}

-- CSS units
M.units = { "px", "em", "rem", "%", "vh", "vw", "vmin", "vmax", "ch", "ex" }

-- Color keywords (subset)
M.colors = {
	"transparent",
	"currentColor",
	"inherit",
	"black",
	"white",
	"red",
	"green",
	"blue",
	"yellow",
	"cyan",
	"magenta",
	"gray",
	"silver",
	"maroon",
	"olive",
	"lime",
	"aqua",
	"teal",
	"navy",
	"fuchsia",
	"purple",
}

return M
